Syslog no
SyslogSuccess no
LogWhy no
UMask 007
Socket inet:8891@0.0.0.0
Mode s
Canonicalization relaxed/relaxed
SignatureAlgorithm rsa-sha256
MinimumKeyBits 2048
KeyTable file:/etc/opendkim/KeyTable
SigningTable refile:/etc/opendkim/SigningTable
InternalHosts refile:/etc/opendkim/TrustedHosts
MacroList daemon_name=ORIGINATING
OversignHeaders From
RequireSafeKeys yes
On-BadSignature tempfail
On-DNSError tempfail
On-InternalError tempfail
On-KeyNotFound tempfail
On-Security tempfail
On-SignatureError tempfail
