# Configuração do OpenDKIM

# Modo de operação
Syslog			yes
UMask			007

# Interface do Milter
Socket			inet:8891@0.0.0.0

# Informações do domínio
Domain			*
KeyTable		/etc/opendkim/KeyTable
SigningTable		refile:/etc/opendkim/SigningTable
ExternalIgnoreList	refile:/etc/opendkim/TrustedHosts
InternalHosts		refile:/etc/opendkim/TrustedHosts

# Logging
LogWhy			yes

#canonicalization	relaxed/simple
